name: KofC6650
options:
  bundleIdPrefix: com.erdman
  deploymentTarget:
    iOS: "16.0"
targets:
  KofC6650:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - KofC6650
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.erdman.kofc6650
        MARKETING_VERSION: "1.0.10"
        CURRENT_PROJECT_VERSION: "5"
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: "KofC 6650"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_NSCalendarsUsageDescription: "Used to add council events to your calendar when you tap \"Add to Calendar.\""
        INFOPLIST_KEY_NSCalendarsFullAccessUsageDescription: "Used to add council events to your calendar when you tap \"Add to Calendar.\""
        INFOPLIST_KEY_NSPhotoLibraryAddUsageDescription: "Used to save a photo to your library when you choose \"Save Image\" from the share sheet."
        ENABLE_PREVIEWS: YES
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: 2ZE6NLQ8E5
  KofC6650ScreenshotUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - KofC6650ScreenshotUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.erdman.kofc6650.screenshotuitests
        SWIFT_VERSION: "5.0"
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 2ZE6NLQ8E5
    dependencies:
      - target: KofC6650
